name: import_ozempic

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  file: ^7.0.1
  analyzer: ">=6.0.0 <9.0.0"
  scoped_deps: ^0.1.0+1
  platform: ^3.1.6
  yaml: ^3.1.3
  glob: ^2.1.3

dev_dependencies:
  test: ^1.26.3
  meta: ^1.17.0
