name: import_ozempic
version: 0.0.1
description: A Dart command-line tool that automatically organizes and cleans up imports in your Dart projects.
repository: https://github.com/mrgnhnt96/import_ozempic

topics:
  - imports
  - automation
  - cli
  - clean

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  file: ^7.0.1
  analyzer: ">=6.0.0 <9.0.0"
  scoped_deps: ^0.1.0+1
  platform: ^3.1.6
  yaml: ^3.1.3
  glob: ^2.1.3
  meta: ^1.17.0

dev_dependencies:
  test: ^1.26.3

executables:
  import_ozempic:
  ioz: import_ozempic.dart
